[workspace]

resolver = "2"
members = ["frontend"]

[workspace.dependencies]

anyhow = "1.0.94"
console_error_panic_hook = "0.1.7"
dynatos = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "775a105501fc04393f9f480a9d7dcba3221bc179" }
dynatos-builder = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "775a105501fc04393f9f480a9d7dcba3221bc179" }
dynatos-context = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "775a105501fc04393f9f480a9d7dcba3221bc179" }
dynatos-html = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "775a105501fc04393f9f480a9d7dcba3221bc179" }
dynatos-loadable = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "775a105501fc04393f9f480a9d7dcba3221bc179" }
dynatos-reactive = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "775a105501fc04393f9f480a9d7dcba3221bc179" }
dynatos-router = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "775a105501fc04393f9f480a9d7dcba3221bc179" }
dynatos-title = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "775a105501fc04393f9f480a9d7dcba3221bc179" }
dynatos-util = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "775a105501fc04393f9f480a9d7dcba3221bc179" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-web = "0.1.3"
url = "2.5.4"
wasm-bindgen = "0.2.99"
web-sys = "0.3.76"
