[workspace]

resolver = "2"
members = ["homepage", "homepage-backend", "homepage-frontend"]

[workspace.package]
authors = ["Filipe Rodrigues <filipejacintorodrigues1@gmail.com>"]
license-file = "LICENSE-MIT"

[workspace.dependencies]

# Workspace
homepage = { path = "homepage" }
homepage-backend = { path = "homepage-backend" }
homepage-frontend = { path = "homepage-frontend" }

axum = "0.8.6"
console_error_panic_hook = "0.1.7"
derive_more = "2.0.1"
dynatos = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "24a76e3f37118434eef10d41c1597e877e5bb7a3" }
dynatos-builder = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "24a76e3f37118434eef10d41c1597e877e5bb7a3" }
dynatos-context = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "24a76e3f37118434eef10d41c1597e877e5bb7a3" }
dynatos-html = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "24a76e3f37118434eef10d41c1597e877e5bb7a3" }
dynatos-loadable = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "24a76e3f37118434eef10d41c1597e877e5bb7a3" }
dynatos-reactive = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "24a76e3f37118434eef10d41c1597e877e5bb7a3" }
dynatos-router = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "24a76e3f37118434eef10d41c1597e877e5bb7a3" }
dynatos-title = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "24a76e3f37118434eef10d41c1597e877e5bb7a3" }
dynatos-util = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "24a76e3f37118434eef10d41c1597e877e5bb7a3" }
reqwest = "0.12.23"
serde = "1.0.228"
tokio = "1.47.1"
toml = "0.9.7"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
tracing-web = "0.1.3"
url = "2.5.7"
wasm-bindgen = "0.2.104"
web-sys = "0.3.81"
zutil-app-error = { git = "ssh://github.com/Zenithsiz/zutil", rev = "978fa5df733d59fc691812ce2fa6072bf901dc7f" }
