[package]
name = "homepage"
version = "0.1.0"
edition = "2021"

[dependencies]

anyhow = "1.0.94"
console_error_panic_hook = "0.1.7"
dynatos = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "b7c31b73fb80fd5231d4ccece4879079623ecb7b" }
dynatos-builder = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "b7c31b73fb80fd5231d4ccece4879079623ecb7b" }
dynatos-context = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "b7c31b73fb80fd5231d4ccece4879079623ecb7b" }
dynatos-html = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "b7c31b73fb80fd5231d4ccece4879079623ecb7b" }
dynatos-loadable = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "b7c31b73fb80fd5231d4ccece4879079623ecb7b" }
dynatos-reactive = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "b7c31b73fb80fd5231d4ccece4879079623ecb7b" }
dynatos-router = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "b7c31b73fb80fd5231d4ccece4879079623ecb7b" }
dynatos-title = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "b7c31b73fb80fd5231d4ccece4879079623ecb7b" }
dynatos-util = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "b7c31b73fb80fd5231d4ccece4879079623ecb7b" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-web = "0.1.3"
url = "2.5.4"
wasm-bindgen = "0.2.99"
web-sys = "0.3.76"
