[package]
name = "homepage"
version = "0.1.0"
edition = "2021"

[dependencies]

anyhow = "1.0.93"
console_error_panic_hook = "0.1.7"
dynatos = { git = "ssh://github.com/Zenithsiz/dynatos" }
dynatos-builder = { git = "ssh://github.com/Zenithsiz/dynatos" }
dynatos-context = { git = "ssh://github.com/Zenithsiz/dynatos" }
dynatos-html = { git = "ssh://github.com/Zenithsiz/dynatos" }
dynatos-loadable = { git = "ssh://github.com/Zenithsiz/dynatos" }
dynatos-reactive = { git = "ssh://github.com/Zenithsiz/dynatos" }
dynatos-router = { git = "ssh://github.com/Zenithsiz/dynatos" }
dynatos-title = { git = "ssh://github.com/Zenithsiz/dynatos" }
dynatos-util = { git = "ssh://github.com/Zenithsiz/dynatos" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-web = "0.1.3"
url = "2.5.4"
wasm-bindgen = "0.2.97"
web-sys = "0.3.74"


[patch."ssh://github.com/Zenithsiz/dynatos"]
dynatos = { path = "../../dynatos/dynatos" }
dynatos-builder = { path = "../../dynatos/dynatos-builder" }
dynatos-context = { path = "../../dynatos/dynatos-context" }
dynatos-html = { path = "../../dynatos/dynatos-html" }
dynatos-loadable = { path = "../../dynatos/dynatos-loadable" }
dynatos-reactive = { path = "../../dynatos/dynatos-reactive" }
dynatos-router = { path = "../../dynatos/dynatos-router" }
dynatos-title = { path = "../../dynatos/dynatos-title" }
dynatos-util = { path = "../../dynatos/dynatos-util" }
