[workspace]

resolver = "2"
members = ["homepage", "backend", "frontend"]

[workspace.package]
authors = ["Filipe Rodrigues <filipejacintorodrigues1@gmail.com>"]
license-file = "LICENSE-MIT"

[workspace.dependencies]

# Workspace
homepage = { path = "homepage" }
homepage-backend = { path = "backend" }
homepage-frontend = { path = "frontend" }

axum = "0.8.1"
console_error_panic_hook = "0.1.7"
derive_more = "1.0.0"
dynatos = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "6a1011f0ad3fdc896b1e117eefddcff7e729e777" }
dynatos-builder = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "6a1011f0ad3fdc896b1e117eefddcff7e729e777" }
dynatos-context = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "6a1011f0ad3fdc896b1e117eefddcff7e729e777" }
dynatos-html = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "6a1011f0ad3fdc896b1e117eefddcff7e729e777" }
dynatos-loadable = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "6a1011f0ad3fdc896b1e117eefddcff7e729e777" }
dynatos-reactive = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "6a1011f0ad3fdc896b1e117eefddcff7e729e777" }
dynatos-router = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "6a1011f0ad3fdc896b1e117eefddcff7e729e777" }
dynatos-title = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "6a1011f0ad3fdc896b1e117eefddcff7e729e777" }
dynatos-util = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "6a1011f0ad3fdc896b1e117eefddcff7e729e777" }
reqwest = "0.12.12"
serde = "1.0.217"
tokio = "1.43.0"
toml = "0.8.19"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-web = "0.1.3"
url = "2.5.4"
wasm-bindgen = "0.2.99"
web-sys = "0.3.76"
zutil-app-error = { git = "ssh://github.com/Zenithsiz/zutil", rev = "978fa5df733d59fc691812ce2fa6072bf901dc7f" }
