[workspace]

resolver = "2"
members = ["homepage", "homepage-backend", "homepage-frontend"]

[workspace.package]
authors = ["Filipe Rodrigues <filipejacintorodrigues1@gmail.com>"]
license-file = "LICENSE-MIT"

[workspace.dependencies]

# Workspace
homepage = { path = "homepage" }
homepage-backend = { path = "homepage-backend" }
homepage-frontend = { path = "homepage-frontend" }

axum = "0.8.3"
console_error_panic_hook = "0.1.7"
derive_more = "2.0.1"
dynatos = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "fb8544f014b4cb620e37639e927ee3f33c8137e0" }
dynatos-builder = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "fb8544f014b4cb620e37639e927ee3f33c8137e0" }
dynatos-context = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "fb8544f014b4cb620e37639e927ee3f33c8137e0" }
dynatos-html = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "fb8544f014b4cb620e37639e927ee3f33c8137e0" }
dynatos-loadable = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "fb8544f014b4cb620e37639e927ee3f33c8137e0" }
dynatos-reactive = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "fb8544f014b4cb620e37639e927ee3f33c8137e0" }
dynatos-router = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "fb8544f014b4cb620e37639e927ee3f33c8137e0" }
dynatos-title = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "fb8544f014b4cb620e37639e927ee3f33c8137e0" }
dynatos-util = { git = "ssh://github.com/Zenithsiz/dynatos", rev = "fb8544f014b4cb620e37639e927ee3f33c8137e0" }
reqwest = "0.12.15"
serde = "1.0.219"
tokio = "1.44.2"
toml = "0.8.20"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-web = "0.1.3"
url = "2.5.4"
wasm-bindgen = "0.2.99"
web-sys = "0.3.76"
zutil-app-error = { git = "ssh://github.com/Zenithsiz/zutil", rev = "978fa5df733d59fc691812ce2fa6072bf901dc7f" }
