[package]
name    = "homepage-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]

# Workspace
homepage-dto = { path = "../homepage-dto" }

app-error                = { workspace = true }
console_error_panic_hook = { workspace = true }
derive_more              = { features = ["full"], workspace = true }
dynatos-loadable         = { workspace = true }
dynatos-reactive         = { workspace = true }
dynatos-web              = { workspace = true }
dynatos-web-reactive     = { workspace = true }
dynatos-web-router       = { workspace = true }
dynatos-web-title        = { workspace = true }
reqwest                  = { features = ["json"], workspace = true }
strum                    = { features = ["derive"], workspace = true }
tracing                  = { features = ["max_level_trace", "release_max_level_info"], workspace = true }
tracing-subscriber       = { workspace = true }
tracing-web              = { workspace = true }
url                      = { workspace = true }
web-sys                  = { workspace = true }
zutil-cloned             = { workspace = true }

[lints]
workspace = true
