[package]
name    = "homepage-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]

# Workspace
homepage = { path = "../homepage" }

app-error                = { workspace = true }
console_error_panic_hook = { workspace = true }
dynatos-web-router       = { workspace = true }
tracing                  = { features = ["max_level_trace", "release_max_level_info"], workspace = true }
tracing-subscriber       = { workspace = true }
tracing-web              = { workspace = true }
web-sys                  = { workspace = true }

[lints]
workspace = true
